---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36
  client_rb:
    environment: development
platforms:
  - name: ubuntu-16.04

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - role[db]
    verifier:
      inspec_tests:
        - test/specs